# Generated by Django 4.1.7 on 2023-03-25 07:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("todolist", "0002_alter_todolist_category"),
    ]

    operations = [
        migrations.AlterField(
            model_name="todolist",
            name="category",
            field=models.ForeignKey(
                default="general",
                on_delete=django.db.models.deletion.CASCADE,
                to="todolist.category",
            ),
        ),
    ]
